### PR TITLE
[MDS-312]  Make hidden components visible on side menu

### PR DESCRIPTION
**Pull request by tkullisaar**

### CODE REVIEW

**Comment by phgrey** [comment]
Aren't we going to add back previously deleted menu items? Regarding old components

**Comment by tkullisaar** [comment]
All other hidden pages are empty at this point. Or which deleted items are you referring to?

**Comment by tkullisaar** [comment]
> Aren't we going to add back previously deleted menu items? Regarding old components

All other hidden pages are empty at this point. Or which deleted items are you referring to?

**Comment by tkullisaar** [comment]
List Item page was removed since Menu Item was there to replace it. Should we still restore List Item?

**Comment by phgrey** [comment]
yes, please restore. and also - please move MenuItem  to Moon.Design namespace and Components V2 in menu

**Review by phgrey — APPROVED** [review]

**Pull request merged**
